import '@ant-design/v5-patch-for-react-19';

import { ConfigProvider } from "antd";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/header/header";
import { Divider } from "antd";
import FooterCustomized from "@/components/footer_customized";
import ar_EG from 'antd/locale/ar_EG';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "مركز تعليمي",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider direction="rtl" locale={ar_EG}>
          <Header />
          <Divider style={{marginBottom: '0'}}/>
          <AntdRegistry>
            {children}
          </AntdRegistry>
          <FooterCustomized />
        </ConfigProvider>
      </body>
    </html>
  );
}
