import '@ant-design/v5-patch-for-react-19';
import { ConfigProvider } from "antd";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import locale from 'antd/locale/ar_EG';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "صفحة المسؤول",
  description: "Generated by create next app",
};

export default function UserLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <html lang="ar" dir="rtl">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ConfigProvider direction="rtl" locale={locale}>
            <AntdRegistry>
                {children}
            </AntdRegistry>
          </ConfigProvider>
        </body>
      </html>
    )
}