import '@ant-design/v5-patch-for-react-19';

import type {Metadata} from "next";
import {auth} from "@/auth";
import {redirect} from "next/navigation";
import {getUserRoleByEmail} from "@/lib/_data_access/users";
import AdminLayout from "@/app/(admin)/admin/admin_layout";
import {MyDetailsComponent} from "@/components/ui/admin_pages/my_details/my_details_component";


export const metadata: Metadata = {
    title: "بياناتي",
    description: "Generated by create next app",
};

export default async function MyDetailsPage() {
    const session = await auth();
    if (!session) {
        redirect("/");
    }

    const userRole = await getUserRoleByEmail(session.user?.email);

    if (userRole !== "admin") {
        return redirect("/");
    }

    return (
        <AdminLayout role={userRole}>
            <MyDetailsComponent />
        </AdminLayout>
    )
}