import '@ant-design/v5-patch-for-react-19';

import React from "react";
import AdminLayout from "@/app/(admin)/admin/admin_layout";

import type {Metadata} from "next";
import {auth} from "@/auth";
import {redirect} from "next/navigation";
import { getUserRoleByEmail } from "@/lib/_data_access/users";
import ReservationsPageMainButtons from "@/components/ui/admin_pages/reservation_pages/reservations_page_main_buttons";

export const metadata: Metadata = {
    title: "صفحة الحجوزات",
    description: "Generated by create next app",
};

export default async function AdminReservationsPage() {

    const session = await auth();
    if (!session) {
        // TODO should redirect to unauthorized page
        // throw new Error("There is an error");
        redirect("/");
    }
    const userRole = await getUserRoleByEmail(session.user?.email);

    if (userRole !== "admin") {
        return redirect("/");
    }

    // TODO change role to
    return (
       // <AdminAuthWrapper>
            <AdminLayout role={userRole}>
                <h2 className='mb-2' style={{ fontSize: "48px", fontWeight: "bold" }}>صفحة الحجوزات</h2>
                <ReservationsPageMainButtons />

            </AdminLayout>
        //</AdminAuthWrapper>
    );
}